title: Reza Dayhool Personal Webpage # your name (or website title) here
logo: "/profile.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
Cyber Security & Electrinic Specialist
<br><br>
<a href="dayhoolengineering@gmail.com">dayhoolengineering@gmail.com </a>
<br>
<a href="https://www.linkedin.com/in/rezadayhool/">Linkedin Profile</a>
<br>
<a href="https://dayhooltech.ir">Resume</a>
theme: jekyll-theme-dinky
